/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AwAlertInterface,
} from './components/alert/alert-component.interface';
import {
  AwTabsInterface,
} from './components/tabs/tabs-component.interface';

export namespace Components {
  interface ActiveTabsComponent {
    'element': HTMLElement;
  }
  interface AlertComponent {
    'message': string;
    'type': 'mega' | 'info' | 'error' | 'success';
  }
  interface TabsComponent {
    'active': boolean;
    'name': string;
  }
}

declare global {


  interface HTMLActiveTabsComponentElement extends Components.ActiveTabsComponent, HTMLStencilElement {}
  var HTMLActiveTabsComponentElement: {
    prototype: HTMLActiveTabsComponentElement;
    new (): HTMLActiveTabsComponentElement;
  };

  interface HTMLAlertComponentElement extends Components.AlertComponent, HTMLStencilElement {}
  var HTMLAlertComponentElement: {
    prototype: HTMLAlertComponentElement;
    new (): HTMLAlertComponentElement;
  };

  interface HTMLTabsComponentElement extends Components.TabsComponent, HTMLStencilElement {}
  var HTMLTabsComponentElement: {
    prototype: HTMLTabsComponentElement;
    new (): HTMLTabsComponentElement;
  };
  interface HTMLElementTagNameMap {
    'active-tabs-component': HTMLActiveTabsComponentElement;
    'alert-component': HTMLAlertComponentElement;
    'tabs-component': HTMLTabsComponentElement;
  }
}

declare namespace LocalJSX {
  interface ActiveTabsComponent {
    'element'?: HTMLElement;
  }
  interface AlertComponent {
    'message'?: string;
    'onAcknowledgeEvent'?: (event: CustomEvent<AwAlertInterface>) => void;
    'type'?: 'mega' | 'info' | 'error' | 'success';
  }
  interface TabsComponent {
    'active'?: boolean;
    'name'?: string;
    'onTabActivate'?: (event: CustomEvent<AwTabsInterface>) => void;
  }

  interface IntrinsicElements {
    'active-tabs-component': ActiveTabsComponent;
    'alert-component': AlertComponent;
    'tabs-component': TabsComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'active-tabs-component': LocalJSX.ActiveTabsComponent & JSXBase.HTMLAttributes<HTMLActiveTabsComponentElement>;
      'alert-component': LocalJSX.AlertComponent & JSXBase.HTMLAttributes<HTMLAlertComponentElement>;
      'tabs-component': LocalJSX.TabsComponent & JSXBase.HTMLAttributes<HTMLTabsComponentElement>;
    }
  }
}


